<?php
	$settings = Settings::getInstance();
?>

<?php get_header(); ?>

	<?php get_template_part( 'template-parts/front-page/content-slider', get_post_format() ); ?>

	<?php get_template_part( 'template-parts/front-page/content-products', get_post_format() ); ?>


	<section>
		<heading>
		</heading>
		<article>
		<div class="container">
			<div class="row">
				<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. At, illo dignissimos rerum id voluptate perspiciatis eius, pariatur fugit tempore debitis repellendus earum explicabo eveniet molestias inventore excepturi quo eum omnis perferendis atque! Alias laudantium, atque dolorem eos, nam cum molestias repellendus aspernatur voluptatem commodi quam quaerat adipisci reprehenderit, obcaecati est? Minima, doloribus repellendus? Alias doloremque vitae blanditiis fugiat, perferendis, natus nisi atque suscipit dolor, ex eos. Et est possimus ipsum commodi debitis quae ex fugiat dicta quis, iure iste sapiente, libero dolore. Laudantium tempore doloribus fuga exercitationem consequuntur non quam, placeat hic iste ipsa a totam magnam voluptate obcaecati ut doloremque magni reiciendis voluptatibus saepe soluta culpa minima harum est. Unde reprehenderit optio ipsum? Ad, eum sint asperiores fugiat autem quam ullam dicta aspernatur ratione dolorum minus numquam officia iure suscipit! Dolores culpa maiores qui quis fugit iure nulla saepe fugiat, quia nostrum quibusdam pariatur accusantium eum, repudiandae quae dolor quo a excepturi magni vitae distinctio expedita iste repellendus soluta! Repellat iusto alias magnam minima dicta saepe non, facilis dolor facere ipsa sed, porro mollitia sit dolorum omnis, ut fugit quo et! Recusandae placeat natus cupiditate doloribus deleniti dolorum, aperiam nobis incidunt sit quo ex repellat obcaecati dolorem, maxime neque.</p>
				<p>Quidem quisquam fugit impedit corporis unde cumque. Illo aperiam, eveniet commodi molestias asperiores placeat dolore odit et molestiae ad. Error est necessitatibus veniam quisquam ullam. Eos labore aliquid quod ipsa aperiam, vel delectus in, sunt dignissimos architecto laudantium ducimus recusandae! Minus dignissimos velit, amet saepe modi quidem provident illum nobis, aperiam cupiditate ipsam nihil dolore? Soluta molestiae saepe exercitationem similique! Nostrum, ab quaerat expedita illum perspiciatis blanditiis iste, corporis velit illo dignissimos nisi veritatis dolorum veniam soluta quisquam deserunt commodi quos cum laudantium. Optio, inventore? Minus, molestiae et? Quas eligendi quo harum ducimus. Sapiente dolorum impedit saepe quam cum repellat fugit! Excepturi voluptates corporis, consequatur nisi architecto labore in maiores ab dolor repellendus facilis, atque aut numquam, tempore doloribus commodi earum modi cupiditate magnam fugit exercitationem. Vero, recusandae. Incidunt accusamus expedita itaque exercitationem deleniti veniam similique praesentium excepturi asperiores, optio in, debitis, nulla numquam assumenda! Libero nobis accusamus ipsa eveniet nulla temporibus? Doloremque eos reprehenderit harum libero ex. Est ea vitae ipsa accusamus, pariatur doloribus optio, quaerat tenetur, aperiam quibusdam similique. Tempore dolores vero reiciendis pariatur rerum suscipit assumenda! Nostrum nemo ratione iure iusto eligendi aliquam deleniti nisi reprehenderit aliquid voluptatem, voluptatibus, tempore est earum accusantium quae fuga odit aut.</p>
				<p>Voluptatibus, saepe harum. Iure nemo fugit soluta quibusdam quo, ab voluptates voluptas molestiae, aspernatur nam eveniet, hic enim quod amet quis eaque cumque id. Aperiam harum eveniet ullam obcaecati facere sed sint corporis. Similique ipsa unde itaque vitae cupiditate eius, accusantium magni aut nobis maiores repellat aperiam, explicabo facilis voluptatem sint eos ad nihil dignissimos dolores pariatur expedita ea laudantium omnis! Iure culpa delectus cupiditate molestias praesentium consequatur eligendi nulla necessitatibus ea totam, laborum earum quo doloremque et, eveniet doloribus minus. Doloribus molestias odit, excepturi animi quod praesentium perspiciatis, rerum voluptatem nemo fugit sunt necessitatibus assumenda rem, laboriosam repellat voluptas laudantium deserunt vel? Corporis atque totam quidem dolorem? Laboriosam necessitatibus tempora excepturi inventore. Eveniet minus rerum incidunt aliquam, totam dolor maxime odio illum beatae officia minima nesciunt, accusantium ut? Perferendis quidem deleniti eaque excepturi quibusdam nisi nesciunt corporis provident vel autem, quo omnis ipsum delectus nulla debitis modi atque, facere obcaecati eius magni ad quia quod vitae. Asperiores accusamus repellat earum eos sequi laudantium est quos aut praesentium odit nulla exercitationem architecto, repudiandae alias possimus rem nam assumenda nihil, quis quaerat facilis. Vero eligendi est nulla veritatis consectetur fugit molestias ex nesciunt! Molestias, eaque! Dolore possimus debitis aut tempora minima?</p>
				<p>Aperiam dicta qui veniam vero autem quos ut temporibus blanditiis, ab ea facilis nihil maxime ullam nostrum alias consequatur officia quia quibusdam debitis optio iusto nesciunt? Ducimus maiores impedit eaque ullam optio ea porro natus quisquam illum, suscipit ratione fugit, rerum vero nobis, iste harum unde et enim culpa animi tempore necessitatibus sint earum! Voluptatem placeat perspiciatis blanditiis inventore nemo voluptas possimus architecto necessitatibus sed enim doloremque et, nihil hic sit corporis tempore eaque aspernatur facilis provident. Deserunt totam at facere accusamus natus modi, libero consequatur, accusantium veritatis cupiditate ad temporibus? Nulla laboriosam assumenda nostrum explicabo asperiores quas pariatur reiciendis magni, exercitationem vitae rem vero et maiores beatae, error, fugit ut repudiandae labore? Quasi ex aliquid repellat asperiores cum laboriosam voluptatem qui ab doloremque libero? Cum accusantium dolorum impedit quis amet quae iusto id architecto praesentium porro voluptatum, atque facere fugiat nobis! Accusamus velit libero necessitatibus voluptate non tempora repellat, modi aut animi, quidem error delectus suscipit cupiditate laborum. Maiores, perferendis? Incidunt cumque consectetur at. Optio distinctio nemo, dolor ea quos, nesciunt magnam ipsa qui in ex quisquam iusto laboriosam laudantium impedit. Maiores itaque veniam quaerat nulla adipisci et, reprehenderit suscipit a exercitationem delectus beatae tempore omnis sit. Dolor, consequuntur.</p>
				<p>Dignissimos, deserunt, hic autem cum at fuga odit accusantium soluta iusto id consequuntur? Iste, pariatur amet modi commodi voluptate optio temporibus, praesentium officia nam dolorem voluptatibus quibusdam id eveniet labore sunt voluptatum at incidunt nesciunt facilis! Aliquam, veritatis ipsum natus, voluptatibus accusantium saepe accusamus nam maiores cumque, ullam corporis. Sed commodi corporis officiis iste et eaque harum dolorum quibusdam alias animi iusto, voluptas neque, velit, illo vitae quis eveniet voluptatem saepe! Neque reprehenderit corporis voluptatum corrupti consequatur. Vitae consequuntur amet eius natus similique, error facere laudantium a, sed consectetur odio ad veniam alias obcaecati. Adipisci temporibus non, aliquid, vel, minima pariatur ullam possimus dolor nostrum aut sapiente doloribus rem cumque iste. Enim eius blanditiis labore similique laborum voluptate quaerat ex tempora, numquam voluptatem natus ipsum omnis assumenda, voluptatibus dolorem repellat. Totam aperiam ullam excepturi eveniet saepe consectetur numquam, fugiat, ratione suscipit quas corporis asperiores blanditiis, necessitatibus ipsum sapiente soluta. Alias saepe ea nihil facilis eius fugiat culpa nesciunt quas error porro tenetur assumenda deleniti voluptatibus, vitae quasi reprehenderit doloremque dolores quisquam corrupti nulla aspernatur sequi dignissimos. Aliquam, rerum! Vel rem voluptatum aspernatur omnis facere temporibus, placeat quasi autem. Nesciunt minima itaque sunt nostrum, provident pariatur fugiat praesentium doloribus officiis aliquid!</p>
				<p>Dolorum beatae, ipsa quos, at quae adipisci odit perspiciatis culpa sapiente magni sit fuga molestias illum quaerat. Ratione voluptate quibusdam ducimus debitis totam facilis autem distinctio est, voluptatibus, quia minus quasi nobis labore, officia laboriosam perferendis sequi. Aliquam cum repellat iure mollitia perferendis porro ex illum consectetur? Amet dolore culpa nostrum fuga obcaecati dolores numquam earum consectetur praesentium asperiores est natus iure hic quibusdam, veniam, fugiat explicabo quam tenetur odit sed magnam! Delectus temporibus placeat, tempore fugit, ex similique laudantium maxime voluptas veniam distinctio nam, culpa explicabo aperiam enim pariatur laboriosam a. Consequuntur doloremque unde tenetur quisquam eaque vel non molestiae provident, tempore sapiente nemo enim iste reprehenderit est adipisci pariatur ratione minima odio nobis a inventore deleniti eos? Sequi obcaecati consectetur dolores ut odio quisquam magnam praesentium officiis adipisci repudiandae eveniet vel laborum modi quis minus facere, quaerat rem quidem minima suscipit repellendus sed fugiat voluptatem vitae. Laboriosam eaque cum in, quam similique officiis quaerat totam, quasi debitis placeat qui pariatur doloremque perspiciatis, reprehenderit rerum explicabo nihil sit? Molestias, repellat. Molestias ipsum dolorem quae fugit rem odit nesciunt asperiores ab tempora omnis quas officiis, ullam odio dignissimos libero repudiandae autem quos culpa. Inventore similique facilis deserunt provident asperiores neque.</p>
				<p>Rerum sed ex esse aspernatur. Inventore optio corporis ab praesentium vero ullam assumenda sit voluptas! Harum esse et, maxime autem similique ducimus molestias, commodi eligendi qui deleniti quo, tenetur tempore doloribus. Consequuntur perferendis magni quia omnis placeat ducimus in dolor sequi vero cupiditate beatae repellendus, porro veritatis quae fugit similique, pariatur eos officiis aperiam sunt, explicabo nemo. Soluta et beatae quibusdam adipisci voluptates non, magni dignissimos architecto assumenda sint quasi ab accusamus rem, iste fugiat error aliquid aut consectetur voluptatem mollitia a modi placeat ratione sed. Esse soluta mollitia quo deleniti quisquam quae nisi, similique dolore rerum voluptate distinctio animi amet hic illum suscipit voluptatem facilis eos! Doloremque dolores cupiditate officiis distinctio, id maxime voluptatum nisi quaerat aperiam nihil sequi velit quae debitis rerum numquam recusandae cumque nostrum voluptas et amet odit architecto deleniti omnis temporibus. Omnis ab nam excepturi. Nostrum deserunt amet sint adipisci fuga voluptatibus quasi quis, beatae modi exercitationem ad suscipit quae dolorum molestias hic reiciendis tenetur, nam distinctio voluptate vero repellendus nisi odio. Expedita consectetur sunt quos reprehenderit magnam, dolorem corrupti. Laboriosam vitae neque, nobis saepe reiciendis ut ducimus doloremque eligendi ipsum rerum architecto cumque sunt tenetur repellat iste? Ab minus voluptas, labore perspiciatis dignissimos nihil!</p>
				<p>Earum enim at quia ab saepe libero eligendi adipisci labore eos doloribus iusto perferendis omnis incidunt repellat, soluta nisi? Laborum eveniet dolore sit porro obcaecati repellat mollitia voluptatibus nihil, asperiores quidem ut sequi ea architecto totam eligendi magni perspiciatis qui repudiandae perferendis cupiditate? Ea nostrum veniam facilis dicta velit, excepturi porro, totam esse maiores sed quam, sint quod? Sed assumenda quam mollitia corrupti voluptatibus iusto labore quis quos ex. Ut quis repudiandae praesentium, corrupti nisi tenetur reiciendis. Quia dolore a nulla nesciunt vero eos soluta, similique repellat at, officia corporis, id accusantium numquam est fugiat quod dignissimos dolorum fugit iure ullam ad alias sapiente. Reiciendis deserunt harum neque? Laudantium reprehenderit fuga quas ea in. Non minima sunt, atque odio omnis ipsa necessitatibus cumque, eius culpa, vel sapiente provident sequi enim! Laudantium repellendus officia harum sed. Dolores praesentium voluptatem quidem voluptates consectetur. Ab voluptates quidem necessitatibus illo soluta, officia doloribus magnam tenetur sunt earum, accusamus, distinctio similique modi explicabo. Sit, necessitatibus alias laboriosam est dolorum sunt nostrum inventore minima praesentium quia suscipit molestiae quisquam quam libero minus voluptates mollitia maxime esse earum animi accusamus nam! Dolores, eveniet quaerat officia adipisci impedit molestiae natus dolore laboriosam perferendis delectus repellendus blanditiis reiciendis aut?</p>
				<p>Optio porro, saepe, enim harum voluptatibus ducimus et provident iusto, a commodi natus est deserunt? Error corporis facilis repudiandae distinctio laboriosam? Quisquam, nulla earum ipsum fugiat deserunt tenetur atque. Vero, mollitia officia, deleniti delectus suscipit ut dolorum doloremque ab nostrum, dolore inventore saepe veritatis qui eum recusandae provident unde rem accusamus vel. Deserunt dolorum laborum suscipit beatae accusantium voluptates doloremque sunt qui soluta debitis animi minus voluptas ipsam aspernatur, commodi libero reiciendis in totam necessitatibus doloribus nihil. Reprehenderit aut cupiditate assumenda ut deleniti quibusdam rem ullam corrupti. Quia assumenda est voluptatem cupiditate atque! Minima quasi ipsum, incidunt rem labore enim expedita impedit dolor? Nihil molestias ad incidunt earum, ab asperiores esse totam ratione ipsum reiciendis commodi repellendus dolor, minus quos quis accusamus nisi repudiandae adipisci impedit! Nemo, dicta error expedita tempore vitae tempora! Voluptate ut eaque perferendis quam non! Sit, quos voluptatum, perferendis praesentium dolores laboriosam sed, ullam assumenda magnam perspiciatis ut temporibus numquam inventore similique? Tempore natus iusto vitae doloremque ratione esse obcaecati, a, ipsum sed pariatur cupiditate, cumque alias voluptas ullam. Accusantium repellat, odit maxime corrupti vero quis animi laudantium eos. Minima accusamus incidunt delectus, ipsa non, minus ut esse quod veniam illo facere eos, in sapiente excepturi?</p>
				<p>Temporibus culpa, neque explicabo ratione sequi debitis magnam quidem possimus, doloremque libero deserunt, magni iure! Voluptates numquam esse, magni at iure porro vel nulla modi hic, architecto eos incidunt rerum alias. Minus eius ipsam dolores placeat tenetur commodi reprehenderit veritatis maxime, optio provident a consequuntur adipisci dolore dolorem eveniet accusamus quia repudiandae explicabo sunt vero qui quasi quaerat. Aut tempora voluptatem quae beatae excepturi libero placeat perspiciatis voluptate repellat delectus officia est architecto animi doloremque, quos harum assumenda. Libero soluta corporis, minima repellat iste alias. Natus libero maxime sint quis officiis illo facere quod error numquam temporibus est praesentium, provident amet quas corporis placeat maiores explicabo nulla rerum obcaecati ipsa quam. Voluptatibus velit magni iste est sequi similique autem fugiat quos dignissimos, dolore perferendis alias quas quisquam nemo, ipsam distinctio, amet placeat ipsum eaque ea! Doloribus totam aperiam obcaecati voluptate iusto laudantium aliquam necessitatibus amet ipsa quae dolores ratione excepturi debitis nostrum at nam architecto, explicabo ex iure, recusandae laboriosam non numquam. Sint, adipisci ipsum. Culpa nihil ullam beatae repudiandae dignissimos voluptas mollitia molestiae repellendus? Eos nam blanditiis vero libero, possimus, aut repudiandae fugiat nisi at aliquid odio optio, illo veniam. Qui saepe fugiat laborum commodi deserunt dolore optio non!</p>
				<p>Ipsam repellendus omnis aperiam accusantium voluptatem deleniti cum est iusto, maiores id porro molestiae sit beatae tenetur ipsa esse molestias odit fugit earum inventore! Similique reprehenderit ullam tempore enim! Quia soluta maiores officia est perspiciatis! Quibusdam quas ab minima est, libero quo officiis facilis sapiente accusantium blanditiis, expedita repudiandae aliquam perspiciatis atque quasi illo pariatur id exercitationem? Doloremque architecto voluptatem, similique ab reiciendis officiis delectus magni. Itaque dolorum numquam accusamus quaerat expedita, similique excepturi laborum consectetur harum ipsum at facere atque voluptas, veritatis, quis ullam voluptate architecto aspernatur deserunt eos. Accusamus tempore amet at necessitatibus id voluptates ullam. Omnis exercitationem, aut delectus voluptatibus culpa pariatur hic obcaecati facere autem perspiciatis soluta veniam necessitatibus saepe error accusantium aliquid unde, ratione nisi, maxime molestiae! Quis dicta inventore, vel enim alias perferendis quidem delectus, recusandae in, corporis quasi necessitatibus. Maiores, quam asperiores possimus, laborum aspernatur deserunt odio cum expedita, similique hic voluptatum corrupti porro quos consectetur! Ut quaerat pariatur impedit excepturi dolores iure recusandae consequuntur ex, alias aperiam exercitationem, fugiat molestiae voluptate vitae! Blanditiis nihil dicta similique repudiandae aliquid distinctio omnis, amet veritatis, accusantium, iure libero asperiores quis dolorum ex consequuntur dolore culpa possimus sapiente est odit. Cupiditate rerum iure cumque? Atque, officia!</p>
				<p>Eligendi ratione doloribus doloremque quasi? Cumque quidem tempora quasi illo totam reprehenderit voluptatem vel aperiam enim labore illum ea, eveniet provident maiores quas mollitia quo? Hic aspernatur consequuntur eos doloribus ipsum aliquam doloremque atque quos, reprehenderit maxime aperiam voluptatem dolores dolorem commodi et quia delectus ad. Aut veritatis fuga laudantium eveniet incidunt aliquam autem deserunt iusto blanditiis consequuntur, inventore animi optio, libero corrupti id repellat dignissimos. Magni eos voluptatem ducimus aliquam libero blanditiis a sunt adipisci, aliquid amet, sequi vitae ipsum. Earum debitis non quia modi amet ut nobis culpa porro ipsam asperiores nostrum, quo quibusdam, repudiandae, sint corporis ab! Velit modi eos sit eum dicta esse perferendis, impedit facere repudiandae eligendi. Non tempora eos dicta? Eius a similique asperiores, provident veniam dignissimos adipisci iste quae esse debitis maxime! Quo unde dicta eos qui, beatae iure nobis eligendi voluptatum repellat dolorum, reiciendis fugit ab nostrum tempora sunt possimus harum deleniti reprehenderit. Odio impedit dolore consectetur! At reiciendis perspiciatis voluptatem repellat tempora ducimus maxime similique sequi non! Sapiente maxime libero quia sint. Placeat quia doloribus illo quaerat id, maxime odio nostrum autem incidunt quibusdam iure dolorum porro ab temporibus laborum eveniet voluptatum necessitatibus eos provident sequi reprehenderit? Ratione ab vel quaerat!</p>
			</div>
		</div>
		</article>

		<heading></heading>
		<article></article>

		<heading></heading>
		<article></article>
	</section>

	<footer></footer>
<?php get_footer(); ?>